"""1-based cycle algebra.

A cycle of length ``q`` generated by the relation ``p ≡ 1 (mod q)``
is represented here as two separate, branch-free quantities:

* ``index``    — the smallest coefficient ``A0 = t mod q``, may be 0.
* ``position`` — the 1-based dial position, ``(t-1) mod q + 1``, never 0.

The distinction is the formal heart of §3.3 of the paper: end and
beginning are different moments, and the transition ``p ≡ 1 (mod q)``
is the model, not a by-product of the division.
"""
from __future__ import annotations

from dataclasses import dataclass

__all__ = ["Cycle", "Decomposition"]


@dataclass(frozen=True, slots=True)
class Decomposition:
    """A single point on a cycle, split into its two answers.

    Attributes
    ----------
    cycles:
        Number of complete cycles that have elapsed before ``t``.
    position:
        1-based dial position in ``1..q``.
    """

    cycles: int
    position: int


@dataclass(frozen=True, slots=True)
class Cycle:
    """A 1-based cycle of length ``q``, optionally generated by ``p``.

    Parameters
    ----------
    q:
        Cycle length, ``q >= 1``.
    p:
        Optional generator. When given, ``p ≡ 1 (mod q)`` is enforced
        at construction time (the "foundation relation" of §2.1).

    Notes
    -----
    The hot-path methods (:meth:`index`, :meth:`position`,
    :meth:`cycles`, :meth:`decompose`, :meth:`transition_count`)
    contain no conditional branches. This is verified mechanically
    by ``tests/test_branchless.py`` and enforced by CI.
    """

    q: int
    p: int | None = None

    def __post_init__(self) -> None:
        if self.q < 1:
            raise ValueError(f"q >= 1 vereist, kreeg q={self.q}")
        if self.p is not None:
            if self.p <= 0:
                raise ValueError(f"p > 0 vereist, kreeg p={self.p}")
            if (self.p - 1) % self.q != 0:
                raise ValueError(
                    f"fundamentele relatie geschonden: "
                    f"p={self.p} ≢ 1 (mod {self.q})"
                )

    # ----------------------------------------------------------- core
    def index(self, t: int) -> int:
        """``A0 = t mod q``. The smallest coefficient on the ladder.

        May be ``0`` for ``t = q, 2q, 3q, ...``. This is *not* a dial
        position; see :meth:`position`.
        """
        return t % self.q

    def position(self, t: int) -> int:
        """1-based dial position in ``1..q``. Never returns 0.

        For ``q = 12``: ``12 -> 12``, ``13 -> 1``, ``24 -> 12``,
        ``25 -> 1``. This is the transition ``p ≡ 1 (mod q)`` made
        explicit as an expression.
        """
        return (t - 1) % self.q + 1

    def cycles(self, t: int) -> int:
        """Number of complete cycles elapsed before ``t``."""
        return (t - 1) // self.q

    def decompose(self, t: int) -> Decomposition:
        """Return both answers at once: cycles and position."""
        return Decomposition(self.cycles(t), self.position(t))

    def transition_count(self, t: int) -> int:
        """Number of end→beginning transitions in ``1..t``."""
        return t // self.q

    # ------------------------------------------------------ convenience
    def walk(self, t: int) -> tuple[int, int]:
        """Legacy alias for :meth:`decompose`, returns a plain tuple."""
        d = self.decompose(t)
        return d.cycles, d.position

    def __repr__(self) -> str:
        if self.p is None:
            return f"Cycle(q={self.q})"
        return f"Cycle(p={self.p}, q={self.q})"
